### ISSUE TITLE
Can I replace eddy_openmp with eddy _ correct in FSL

### ISSUE THREAD

**Issue by Defuse3** [gbarisano/alps#1]
I can't use the eddy_openmp function in FSL and the correction is time-consuming. can I change it to eddy _ correct?

And I can't find the article you asked me to cite, has it not been online yet?

**Comment by gbarisano** [comment]
Hello. I have updated my pipeline to allow the user to choose the eddy_correct command from $FSLDIR/bin/ . This can now be chosen with the option ```-e 3```.
Give it a try!

Our article is currently in press and will be online soon! If you are submitting a paper right now, please just include the reference as is in the README file and the link to this repository. By the time your paper will be online, our paper should be online too! Thank you!
