### ISSUE TITLE
Image Exception : #63 :: No image files match: my_4D_dwi No image files match: my_4D_dwi

### ISSUE THREAD

**Issue by Chloefu1994** [gbarisano/alps#2]
(base) bogon:raw_data_alp chole$ bash alps.sh -a my_4D_dwi.nii.gz -b my_bval_file.txt -c my_bvec_file.txt -m my_bids_file.json -d 0 -e 0
ROI analysis with default ROIs
Default FA template will be used: JHU-ICBM-FA-1mm.nii.gz
Running ALPS with the following parameters: 

-a my_4D_dwi.nii.gz 

-b my_bval_file.txt 

-c my_bvec_file.txt 

-m my_bids_file.json 

-i  

-j  

-k  

-n  

-d 0 

-e 0 

-r /Users/chole/DTI_test/raw_data_alp/ROIs_JHU_ALPS/L_SCR.nii.gz,/Users/chole/DTI_test/raw_data_alp/ROIs_JHU_ALPS/R_SCR.nii.gz,/Users/chole/DTI_test/raw_data_alp/ROIs_JHU_ALPS/L_SLF.nii.gz,/Users/chole/DTI_test/raw_data_alp/ROIs_JHU_ALPS/R_SLF.nii.gz 

-t /Users/chole/fsl/data/atlases/JHU/JHU-ICBM-FA-1mm.nii.gz 

-v  

-h 1 

-w 0 

-s 0 

-o 
create output directory: /Users/chole/DTI_test/raw_data_alp/alps
Denoising and unringing skipped by the user (-d 0 option)
Image Exception : #63 :: No image files match: my_4D_dwi
No image files match: my_4D_dwi
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/b0
Image Exception : #22 :: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/b0
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/b0
libc++abi: terminating due to uncaught exception of type std::runtime_error: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/b0
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/b0
/Users/chole/fsl/share/fsl/bin/bet2: line 2:  7404 Abort trap: 6           /Users/chole/fsl/bin/bet2 "$@"
starting DTI FITTING on input diffusion data (NO preprocessing (denoising/unringing), NO TOPUP, NO eddy correction)
Image Exception : #63 :: No image files match: my_4D_dwi
Image Exception : #22 :: Failed to read volume my_4D_dwi.nii.gz
Error : No image files match: my_4D_dwi
libc++abi: terminating due to uncaught exception of type std::runtime_error: Failed to read volume my_4D_dwi.nii.gz
Error : No image files match: my_4D_dwi
/Users/chole/fsl/share/fsl/bin/dtifit: line 2:  7406 Abort trap: 6           /Users/chole/fsl/bin/dtifit "$@"
DTI FITTING completed!
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dti_tensor
libc++abi: terminating due to uncaught exception of type std::runtime_error: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dti_tensor
/Users/chole/fsl/share/fsl/bin/fslsplit: line 2:  7408 Abort trap: 6           /Users/chole/fsl/bin/fslsplit "$@"
cp: /Users/chole/DTI_test/raw_data_alp/alps/vol0000.nii.gz: No such file or directory
cp: /Users/chole/DTI_test/raw_data_alp/alps/vol0003.nii.gz: No such file or directory
cp: /Users/chole/DTI_test/raw_data_alp/alps/vol0005.nii.gz: No such file or directory
starting ROI analysis with projection fibers L_SCR.nii.gz (LEFT) and R_SCR.nii.gz (RIGHT), and association fibers L_SLF.nii.gz (LEFT) and R_SLF.nii.gz (RIGHT)
Linear registration to template with flirt and default options
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dti_FA
Image Exception : #22 :: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dti_FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dti_FA
Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dti_FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dti_FA
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx
Image Exception : #22 :: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dxx.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx
Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dxx.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dyy
Image Exception : #22 :: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dyy.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dyy
Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dyy.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dyy
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dzz
Image Exception : #22 :: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dzz.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dzz
Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dzz.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dzz
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA
Image Exception : #22 :: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA
Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA
Image Exception : #22 :: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA
Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dyy_in_JHU-FA
Image Exception : #22 :: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dyy_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dyy_in_JHU-FA
Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dyy_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dyy_in_JHU-FA
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dzz_in_JHU-FA
Image Exception : #22 :: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dzz_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dzz_in_JHU-FA
Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dzz_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dzz_in_JHU-FA
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA
Image Exception : #22 :: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA
Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA
Image Exception : #22 :: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA
Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dxx_in_JHU-FA
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dyy_in_JHU-FA
Image Exception : #22 :: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dyy_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dyy_in_JHU-FA
Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dyy_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dyy_in_JHU-FA
Image Exception : #63 :: No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dzz_in_JHU-FA
Image Exception : #22 :: Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dzz_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dzz_in_JHU-FA
Failed to read volume /Users/chole/DTI_test/raw_data_alp/alps/dzz_in_JHU-FA.nii.gz
Error : No image files match: /Users/chole/DTI_test/raw_data_alp/alps/dzz_in_JHU-FA

Parse error: bad expression
    <stdin>:1

Parse error: bad expression
    <stdin>:1

Parse error: bad expression
    <stdin>:1

Finito! Please cite this repository (https://github.com/gbarisano/alps/) and the paper:
Liu, X, Barisano, G, et al., Cross-Vendor Test-Retest Validation of Diffusion Tensor Image Analysis along the Perivascular Space (DTI-ALPS) for Evaluating Glymphatic System Function, Aging and Disease (2023)

**Comment by gbarisano** [comment]
Hi Chloe,

From your code I note that you launch the pipeline without reporting the full path to your data, but only the file name, for example my_4D_dwi.nii.gz. 
You should either cd to the folder where the nifti file is located and then launch the pipeline, or you should include the full path of the inputs that you use in the pipeline (e.g., /Users/chole/DTI_test/raw_data_alp/my_4D_dwi.nii.gz).

I hope this helps!

**Comment by gbarisano** [comment]
Hi Chloe,

I updated my pipeline to be able to use the inputs located in your current working directory without the need to specify the full path. Let me know if this solved your issue.
