### ISSUE TITLE
Potential tensor extraction issue

### ISSUE THREAD

**Issue by qtalwaysrun** [gbarisano/alps#4]
Hi,

In the [recent commit](https://github.com/gbarisano/alps/commit/4376d43bac9f3297f58f03690948b6c1921ce7eb) three weeks ago, I noticed that extraction of tensor components `dxx`, `dyy`, `dzz` was changed from 0, 3, 5 (found at the beginning before the change) to 0, 2, 5 (found at the end after the change). After a test run I found that the final alps values were larger than expected. Since FSL's tensor order is `[Dxx, Dxy, Dxz, Dyy, Dyz, Dzz]`, I was wondering if this was a typo?

Thanks!

**Comment by gbarisano** [comment]
Hi,

Thank you so much for noticing this. Yes, this was a typo. I apologize.

Thanks again,
Giuseppe
