### ISSUE TITLE
how to extract FA and MD values from projection and association areas

### ISSUE THREAD

**Issue by Defuse3** [gbarisano/alps#6]
I greatly appreciate your tool; it has been extremely helpful to me. Currently, many studies exclude the potential impact of white matter microstructure on the ALPS by using the same ALPS ROIs to extract FA and MD values from projection and association areas. They then use the average FA/MD values from the left and right projection and association areas as covariates in statistical analyses. Could you please advise me on how to obtain the FA and MD values from these specific regions using your tool?

**Comment by gbarisano** [comment]
Hello! Thank you for using and appreciating my tool!

I added a function that calculates FA and MD values in the right and left projection and association areas, as well as the average FA and MD of the two sides of projection and association areas.
Download the latest version of the pipeline and give it a try if you'd like!
Let me know if there are issues!   

Giuseppe
