### ISSUE TITLE
eddy_openmp & eddy_cpu

### ISSUE THREAD

**Issue by QunjunLIANG** [gbarisano/alps#7]
Hi Giuseppe,

Thank you for developing such an excellent tool for estimating DTI-ALPS.

I have noticed that the eddy correct comment eddy_openmp is deprecated in FSL 6.0.6 [here](https://github.com/Washington-University/HCPpipelines/issues/264).

Do you consider to provide a option to switch eddy_openmp to eddy_cpu to fit the current FSL version?

Best,
Qunjun

**Comment by gbarisano** [comment]
Hi Qunjun,

Thank you for appreciating my tool!

Great point, thank you! I just changed the default eddy_openmp to ```eddy_cpu```.  
Keep in mind that with the option -e you can specify whichever version of eddy you want to use in my pipeline (e.g., ```-e eddy_cpu```), as long as it is located in ```${FSLDIR}/bin/```.

Best,
Giuseppe
